version: "3"

services:
    helloworld-api:
        container_name: helloworld-api
        build: ./api
        ports:
            - 5000:5000

    helloworld-web:
        container_name: helloworld-web
        build: ./web
        volumes:
            - build-react:/var/www/html
        depends_on:
            - helloworld-api

    nginx:
        container_name: helloworld-nginx
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - build-react:/var/www/html
        depends_on:
            - helloworld-web

volumes:
    build-react:
